### ISSUE TITLE
Print and Download Annotated options are not working

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#21]
This issue was originally raised via forum thread: This issue was originally raised via forum thread: https://forum.groupdocs.com/t/multipage-tiff-not-working/6882/2

Hi,

The **Print** and **Download Annotated** options are not working. I have highlighted both options in below screenshot. Thanks

![download and print button](https://user-images.githubusercontent.com/29034002/50534202-417ab100-0b5b-11e9-92c8-046794a045e3.png)

**Comment by egorovpavel** [comment]
@samicheemagroupdocs The issue has been fixed. Rebuild the solution and clear cache in your browser.

**Comment by bobkovalex** [comment]
@samicheemagroupdocs please confirm if issue is gone.
Thanks

**Comment by samicheemagroupdocs** [comment]
@bobkovalex/ @egorovpavel I am unable to see the saved annotations in printed document. While downloading feature is working fine. Thanks

**Comment by bobkovalex** [comment]
@samicheemagroupdocs please provide more detailed information so that we can reproduce the bug.
Which browser do you use? What version? Did you cleaned cache before building project?
Thanks.

**Comment by samicheemagroupdocs** [comment]
@bobkovalex I am using Google Chrome Version 71.0.3578.98 (Official Build) (64-bit). Yes, I cleaned cache before build/run project. Furthermore, print option is adding blank page before and after the actual page of the document. Please see the below screenshot for further reference. Thanks
![groupdocs](https://user-images.githubusercontent.com/29034002/50604451-d4f80d00-0ee0-11e9-9999-aa0b14c04268.png)

**Comment by egorovpavel** [comment]
@samicheemagroupdocs we were unable to reproduce a described issue, please share the document you are using.

**Comment by samicheemagroupdocs** [comment]
@egorovpavel please find attached sample document I am using. Thanks
[sample.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/files/2727444/sample.pdf)

**Comment by egorovpavel** [comment]
@samicheemagroupdocs we released the fix, please update this sample to the latest version and let us know if it solves an issue.

**Comment by samicheemagroupdocs** [comment]
@egorovpavel thanks for the update. This issue has been resolved in the latest version.
