### ISSUE TITLE
Render file on page load when file is saved on Azure storage

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#43]
Hello,
Can you please tell, how to render a file on page load when file is available at Azure storage? There is an option "defaultDocument" in configuration.yml. I set it to 'D:\Documents\sample.pdf' but its not even rendering/opening sample.pdf that is available in local directory.
Then how to open a document on page load saved on Azure?
Thanks 

This issue is raised here https://forum.groupdocs.com/t/groupdocs-upgrade/7399/3.

**Comment by Pavel-Teplitsky** [comment]
Hi @atirtahirgroupdocs , We have fixed issue with default document, please pull latest version from this repository.

As for the using Azure storage - unfortunatly current version of the example doesn't supports integration with cloud storages. But you can investigate this [documentation](https://docs.groupdocs.com/display/annotationnet/Basic+Concept) for how to work with different storage types.

Best regards
