### ISSUE TITLE
Uncaught reference errors

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#47]
Hi,
I downloaded this project. It was built successfully. But there is no output, nothing renders in the browser. However, there are errors in the console. Please see the screenshot attached. 
![issue](https://user-images.githubusercontent.com/15940608/65277833-37af3880-db44-11e9-8947-e1494269f3ce.JPG)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs i tried to checkout current master branch 
 on commit `c451232d459afc2eb2b18ada8d63585d4e59ebf1` then just ran the solution from VS using F5 and got working app in the browser, could you please clarify your steps for getting these errors?

**Comment by atirtahirgroupdocs** [comment]
@kegor ,

When I host this project as it is to the IIS then I face this issue. 
Steps I followed to host:

- Clean and build project
- Published to a target location 
- Set configuration to release 
- Opened IIS and created a new site/application pool there 
- Browsed website 

![iis config](https://user-images.githubusercontent.com/15940608/65312115-4a108d00-dbab-11e9-92d5-37b6eb1566df.JPG)

Please tell me if there is something wrong.

**Comment by atirtahirgroupdocs** [comment]
@kegor any update on this?
Thanks

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, required changes were merged into master branch in the related PR, could you please retry your steps and let us know if this fix works for you.

**Comment by atirtahirgroupdocs** [comment]
@kegor yes previous issue is fixed, UI is now rendered in the browser. But see what happens when I click on browse file icon:

![click](https://user-images.githubusercontent.com/15940608/65453213-2cb61a00-de5c-11e9-9244-6dbb13e097d9.png)
![console](https://user-images.githubusercontent.com/15940608/65453239-3a6b9f80-de5c-11e9-9e14-0afb979e9f04.png)

This issue is also reproduced at customer's end as well. 
This issue is raised in this thread https://forum.groupdocs.com/t/groupdocs-annotation-for-net-browse-files/7569.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, we searching the correct solution to make it working simultaneously from Visual Studio and on IIS. For now we can only suggest the temporary work-around — you could add the sub-application under your annotation site, specify alias annotation and set the same physical path to the files.

![koNXJ9FhTVCWUpUDkg4wXA](https://user-images.githubusercontent.com/17431807/65530113-05188d80-df00-11e9-8624-c2cc4a084b20.png)

**Comment by atirtahirgroupdocs** [comment]
@kegor thanks for the workaround it worked out.
