### ISSUE TITLE
Annotation Alignment Issue with Images

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#50]
This issue is raised in https://forum.groupdocs.com/t/annotation-alignment-issue-with-images-api-asp-net-mvc-demo/7978
Hi,
When we open/load images, the container/canvas that the image is loaded on is larger than the width/height of the image. This difference is causing some alignment issues when trying to annotate the image.
This is how annotation is being added: http://prntscr.com/qvfakz. I added polyline annotation across full car.
As you can see, the white part (container/canvas) containing the image extends beyond the dimensions of the image itself. This results in the annotation on the image to be misaligned after saving. 
Result: 
![output](https://user-images.githubusercontent.com/15940608/73517338-02cdbf00-441d-11ea-943d-8d21b2989c28.jpg)

Thanks

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

This issue has been fixed.

Before running the project make sure that [@groupdocs.examples.jquery/annotation](https://www.npmjs.com/package/@groupdocs.examples.jquery/annotation) has been updated to latest version.

Latest version is v0.16.8.

**Please note** that current fix was applied to jQuery version of GroupDocs.Annotation, however we are expecting to release Angular version by the end of this month, after that jQuery version will be discontinued.

Thanks.
