### ISSUE TITLE
.NET Blazor sample application

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#62]
This query is raised in https://forum.groupdocs.com/t/net-blazor-samples/9355
Hi,
Is there a plan to develop a sample application showing GroupDocs with .Net 5 Blazor? 
Thanks

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

We do not have any plans on developing a sample on Blazor yet.

Thanks.
