### ISSUE TITLE
Document annotation project with REACT JS

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#65]
https://forum.groupdocs.com/t/need-groupdocs-annotation-tool-in-net-mvc-project-with-react-js/9521
Hi,
Is there a plan to develop a documentation Annotation project with REACT JS?

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

Unfortunately not.

Best Regards
