### ISSUE TITLE
Modifying client side code but no impact in the output

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#66]
This issue is raised in https://forum.groupdocs.com/t/how-i-can-modify-the-angular-client-side-end-features/9527/5.
Hi,
Please have a look at the attached image. There is some code updated in common components folder but those changes are not updated in the browser/app. The annotation folder files are working and updating fine, but the issue only in the common-components folder, in this folder files are not updating.
![image (1)](https://user-images.githubusercontent.com/15940608/113913212-7de6ee00-97f5-11eb-824d-9838773695ed.png)

**Comment by Pavel-Teplitsky** [comment]
Resolved on forum
